DomainList:
  ac: Drutiny\Acquia\AcquiaCloudDomainList
  acsf: Drutiny\Acquia\AcquiaSiteFactoryDomainList
CredentialSchema:
  acquia_api_v1:
    email:
      type: string
      description: Your Acquia account email address
    key:
      type: string
      description: Your API key to connect to the Acquia Cloud API v1 with:
  acquia_api_v2:
    key_id:
      type: string
      description: |
        Your Key ID to connect to the Acquia Cloud API v2 with. To generate an
        API access token, login to https://cloud.acquia.com, then visit
        https://cloud.acquia.com/#/profile/tokens, and click **Create Token**:
    secret:
      type: string
      hidden: true
      description: Your API secret to connect to the Acquia Cloud API v2 with:
